
### 20. `main.py`

Use the following as the final entry point:

```python
import asyncio
from datetime import datetime, timezone

from domain.models import Incident, WorkerTask

from workers.logs import LogsWorker
from workers.registry import DefaultWorkerRegistry

from application.scheduler import LocalScheduler
from application.aggregator import EvidenceAggregator
from application.hypothesis import HypothesisGenerator
from application.assessor import InvestigationAssessor
from application.decision import DecisionEngine
from application.risk import RiskAnalyzer
from application.policy import PolicyEngine
from application.authorization import ActionAuthorization

from execution.server_restart import ServerRestartExecutor
from execution.retry import RetryPolicy

from verification.service_verifier import ServiceVerifier


async def main():

    # --------------------------------------------------
    # 1. Incoming Alert
    # --------------------------------------------------

    incident = Incident(
        incident_id="INC-1001",
        service="payments-api",
        alert_type="database_timeout",
        severity="P1",
        environment="production",
        started_at=datetime.now(timezone.utc),
    )

    # --------------------------------------------------
    # 2. Worker Infrastructure
    # --------------------------------------------------

    registry = DefaultWorkerRegistry(
        [
            LogsWorker(),
        ]
    )

    scheduler = LocalScheduler(
        registry=registry,
        timeout_seconds=5,
    )

    # --------------------------------------------------
    # 3. Initial Execution Plan
    #
    # Currently hardcoded.
    # Later this will be generated by Planner.
    # --------------------------------------------------

    plan = [
        WorkerTask(
            task_id="task-1",
            capability="logs_analysis",
            parameters={
                "service": incident.service,
            },
        )
    ]

    # --------------------------------------------------
    # 4. Execute Workers
    # --------------------------------------------------

    worker_results = await scheduler.execute(
        plan,
        incident,
    )

    # --------------------------------------------------
    # 5. Aggregate Evidence
    # --------------------------------------------------

    evidence_assessment = (
        EvidenceAggregator().aggregate(
            worker_results,
            [],
        )
    )

    # --------------------------------------------------
    # 6. Generate Hypotheses
    # --------------------------------------------------

    hypotheses = (
        HypothesisGenerator().generate(
            incident,
            evidence_assessment.evidence,
        )
    )

    # --------------------------------------------------
    # 7. Assess Investigation
    # --------------------------------------------------

    investigation = (
        InvestigationAssessor().assess(
            incident,
            evidence_assessment.evidence,
            hypotheses,
        )
    )

    print("\n==============================")
    print("INCIDENT")
    print("==============================")

    print(incident)

    print("\n==============================")
    print("EVIDENCE")
    print("==============================")

    for evidence in evidence_assessment.evidence:
        print(
            f"- {evidence.observation}"
            f" | confidence={evidence.confidence}"
        )

    print("\n==============================")
    print("HYPOTHESES")
    print("==============================")

    for hypothesis in hypotheses:

        print(
            f"- {hypothesis.hypothesis_id}: "
            f"{hypothesis.statement} "
            f"(confidence={hypothesis.confidence})"
        )

    print("\n==============================")
    print("INVESTIGATION ASSESSMENT")
    print("==============================")

    print(investigation)

    # --------------------------------------------------
    # 8. Investigation Loop
    #
    # Later this becomes a LangGraph conditional edge:
    #
    # insufficient → Planner
    # sufficient   → Decision
    # --------------------------------------------------

    if not investigation.sufficient_evidence:

        print(
            "\nEvidence insufficient."
        )

        print(
            "Planner should investigate further."
        )

        return

    # --------------------------------------------------
    # 9. Incident Decision
    # --------------------------------------------------

    decision = (
        DecisionEngine().make_decision(
            incident,
            hypotheses,
            investigation,
        )
    )

    # --------------------------------------------------
    # 10. Risk Assessment
    # --------------------------------------------------

    risk = (
        RiskAnalyzer().evaluate_risk(
            incident,
            decision,
            decision.proposed_action,
        )
    )

    # --------------------------------------------------
    # 11. Deterministic Policies
    # --------------------------------------------------

    policies = [

        {
            "policy_id": "P1-PROD-RESTART-HITL",

            "description": (
                "P1 production restart "
                "requires human approval"
            ),

            "conditions": {
                "environment": "production",
                "severity": "P1",
                "action": "restart_server",
            },

            "outcome": "HITL",
        }
    ]

    # --------------------------------------------------
    # 12. Policy Evaluation
    # --------------------------------------------------

    policy_evaluation = (
        PolicyEngine().evaluate(
            incident=incident,
            decision=decision,
            action=decision.proposed_action,
            risk=risk,
            policies=policies,
        )
    )

    # --------------------------------------------------
    # 13. Authorization
    # --------------------------------------------------

    route = (
        ActionAuthorization().authorize(
            incident=incident,
            action=decision.proposed_action,
            risk=risk,
            policy=policy_evaluation,
        )
    )

    print("\n==============================")
    print("DECISION")
    print("==============================")

    print(decision)

    print("\n==============================")
    print("RISK")
    print("==============================")

    print(risk)

    print("\n==============================")
    print("POLICY")
    print("==============================")

    print(policy_evaluation)

    print("\n==============================")
    print("AUTHORIZATION")
    print("==============================")

    print(route)

    # --------------------------------------------------
    # 14. Authorization Gate
    # --------------------------------------------------

    if route.mode == "REJECT":

        print(
            "\nAction rejected."
        )

        return

    # --------------------------------------------------
    # 15. Human-in-the-loop
    # --------------------------------------------------

    if route.mode == "HITL":

        approval = input(
            "\nHuman approval required. "
            "Approve? [y/N]: "
        ).strip().lower()

        if approval != "y":

            print(
                "Human rejected action."
            )

            return

    # --------------------------------------------------
    # 16. Execute
    # --------------------------------------------------

    executor = ServerRestartExecutor()

    verifier = ServiceVerifier()

    retry_policy = RetryPolicy(
        max_attempts=2
    )

    attempt = 1

    while True:

        execution_result = (
            await executor.execute(
                action=decision.proposed_action,
                incident=incident,
                attempt=attempt,
            )
        )

        # --------------------------------------------------
        # 17. Verify
        # --------------------------------------------------

        verification = (
            await verifier.verify(
                incident,
                execution_result,
            )
        )

        print("\n==============================")
        print("EXECUTION")
        print("==============================")

        print(execution_result)

        print("\n==============================")
        print("VERIFICATION")
        print("==============================")

        print(verification)

        # --------------------------------------------------
        # 18. Success
        # --------------------------------------------------

        if verification.verified:

            print(
                "\nIncident resolved."
            )

            return

        # --------------------------------------------------
        # 19. Bounded Retry
        # --------------------------------------------------

        if not retry_policy.should_retry(
            attempt
        ):

            print(
                "\nRemediation exhausted."
            )

            print(
                "Planner should investigate again."
            )

            return

        attempt += 1    


if __name__ == "__main__":
    asyncio.run(main())